name: Auto Stock Scraper

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install gspread oauth2client feedparser vaderSentiment
          
      - name: Run script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDS" > credentials.json
          python stock_news.py
